version: "3"

services:
  mydb:
    container_name: mydb
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password@Project221
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - "./db/int221_init.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/int221_grant.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./db/int221_insert.sql:/docker-entrypoint-initdb.d/3.sql"
  backend:
    container_name: backend
    build: 
      context: ./backend-dev
    image: devops_backend
    ports:
      - "8081:8081"
    depends_on: 
      - mydb
  fontend:
    container_name: fontend
    build:
      context: .
    image: devops_fontend
    ports:
      - "80:80"
    depends_on: 
      - backend


networks:
  default:
    external:
      name: project-network
  