networks:
  project-network:
services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: 'localhost'
    ports:
      - "3306:3306"
    volumes:
      - "./db/int221_init.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/int221_grant.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./db/int221_insert.sql:/docker-entrypoint-initdb.d/3.sql"
    networks:
      - project-network
  backend:
    container_name: backend
    build:
      context: ./backend-dev
    ports:
      - "8081:8081"
    depends_on:
      - "db"
    networks:
      - project-network
  fontend:
    container_name: fontend
    build:
      context: ./fontend-master
    ports:
      - "8080:80"
    depends_on:
      - "backend"
    networks:
      - project-network
  web:
    image: nginx:stable-alpine
    container_name: reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - project-network
  
  